services:
  - type: web
    name: risk-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python xauusd_btc_risk_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
